### ISSUE TITLE
Not show the taxonomies list.

### ISSUE THREAD

**Issue by walkeraguilar** [sectsect/wp-tag-order#69]
On the configuration screen, after the next words, not show the taxonimies list, not show nothing.

General Settings
Enable for these taxonomies

I have a custom post type called videos and I need select that taxonomie.

And on edit custom post type page not show the tags list and I cant reorder.

Thanks

**Comment by sectsect** [comment]
@walkeraguilar 

Thanks for your feedback.

I recommend checking the following:

- Ajax requests to `/wp-admin/admin-ajax.php` are blocked due to additional verification by another plugin, such as a security plugin
- Using WP Tag Order v3.6.x or lower and Chrome v127 or later
- PHP version does not meet the requirements

**Comment by walkeraguilar** [comment]
I have Php 8.2 and where I can download the version 3.6.x please.

**Comment by sectsect** [comment]
For PHP 8, v.3.7.x (`master` branch) is fine.

Make sure that Ajax requests to `/wp-admin/admin-ajax.php` are not rejected.

If the problem persists, I would recommend disabling other plugins and checking.

**Comment by sectsect** [comment]
Hi there,

We’re closing this issue due to a lack of recent activity. If you believe this issue is still relevant or have additional information to share, please feel free to reopen it or create a new issue.

Thank you for your understanding and contribution! 🙌
